### PR TITLE
Fix NullSafe causing ReflectiveAccessorOptimizer use a variable instead of value from the context

### LINKED ISSUE #370: NullSafe may cause resolution of the next step to involve variables instead of the next property
If NullSafe is involved, it calls another call to optimizeAccessor(). However, ReflectiveAccessorOptimizer.optimizeAccessor() will initially assume it is the first invocation and also possibly select the value from a variable. If the next property shares the same name as a variable, the variable will take precedence, thus resulting in incorrect evaluation as it won't take the expected value from the present context.

Here are the known conditions for this bug to occur:
* A compiled expression must be used.
* There must be a null-safe operator in the expression.
* The first invocation must involve a null at the null-safe operator's evaluation.
* There must be a variable that shares the same name as the segment which the null-safe operator evaluates.

Test:
```
		String expression = "foo.?bar.baz"; // "baz" shadows the variable named "baz".

		final String expectedResult = "You got me!";

		Map<String, Object> foo = new HashMap<>();
		Map<String, Object> ctx = Collections.singletonMap("foo", foo);
		Map<String, Object> bar = Collections.singletonMap("baz", expectedResult);
		foo.put("bar", null); // start with null, as this will cause NullSafe to be added to the AST.

		// This variable overlaps the segment to be resolved next after NullSafe.
		Map<String, Object> vars = Collections.singletonMap("baz", "no, over here!");

		Serializable compiledExpr = MVEL.compileExpression(expression);
		System.out.println("output: " + MVEL.executeExpression(compiledExpr, ctx, vars));

		foo.put("bar", bar);
		System.out.println("output: " + MVEL.executeExpression(compiledExpr, ctx, vars));
```

Output:
```
output: null
output: no, over here!
````

Expected output:
```
output: null
output: You got me!
```

### PR DESCRIPTION
**Pull request by sp193**
Fixes #370.

### CODE REVIEW

**Comment by sp193** [comment]
This patch will mean NullSafe cannot be used with variables. But I don't think that completely works anyway, even right now. I cannot tell what's the intended behaviour for NullSafe and variables.

If we want it to work with variables, we need to indicate to NullSafe whether the traversal in AST is the at the first node or not. Other modifications (e.g. to allow NullSafe to work with a null context) may be required.

**Comment by tkobayas** [comment]
@sp193 Thank you for the PR. Could you add a unit test as you wrote in https://github.com/mvel/mvel/issues/370 ? I think `MvelCompileExpNullSafeTest.java` is a good place.

**Comment by sp193** [comment]
I have updated the commit to include a JUnit test. I have updated the first post to reflect the updated test, which is simpler.

**Comment by tkobayas** [comment]
Thanks @sp193 ,

>  I cannot tell what's the intended behaviour for NullSafe and variables.

Yeah, http://mvel.documentnode.com/#null-safe-bean-navigation doesn't tell anything about variables. So I think we don't have a clear answer. But I agree that the issue you reported https://github.com/mvel/mvel/issues/370 is something to be fixed.

> This patch will mean NullSafe cannot be used with variables.

Could you help me to understand use cases where users may want to use "NullSafe with variables"?

I think of only this expression `foo.?bar[myvar]`.

```
String expression = "foo.?bar[myvar]";

final String expectedResult = "You got me!";

Map<String, Object> foo = new HashMap<>();
Map<String, Object> ctx = Collections.singletonMap("foo", foo);
Map<String, Object> bar = Collections.singletonMap("baz", expectedResult);
foo.put("bar", null); // start with null, as this will cause NullSafe to be added to the AST.

Map<String, Object> vars = new HashMap<>();
vars.put("myvar", "baz");

Serializable compiledExpr = MVEL.compileExpression(expression);
Assert.assertNull(MVEL.executeExpression(compiledExpr, ctx, vars));

foo.put("bar", bar);
Assert.assertEquals(expectedResult, MVEL.executeExpression(compiledExpr, ctx, vars));
```

Any other use cases in your mind?

**Comment by tkobayas** [comment]
Ah, another use case. Variable as a method call argument : `foo.?bar.convert(myvar)`.

```
	@Test
	public void testNullSafeVariableOverlapWithVariableAsMethodArg() {
		String expression = "foo.?bar.convert(myvar)";

		Map<String, Object> foo = new HashMap<>();
		Map<String, Object> ctx = Collections.singletonMap("foo", foo);
		foo.put("bar", null); // start with null, as this will cause NullSafe to be added to the AST.

		Map<String, Object> vars = new HashMap<>();
		vars.put("myvar", "hello");

		Serializable compiledExpr = MVEL.compileExpression(expression);
		Assert.assertNull(MVEL.executeExpression(compiledExpr, ctx, vars));

		foo.put("bar", new StringConverter());
		Assert.assertEquals("HELLO", MVEL.executeExpression(compiledExpr, ctx, vars));
	}

	public class StringConverter {
		public String convert(String value) {
			return value.toUpperCase();
		}
	}
```

**Comment by sp193** [comment]
Hi again,

Actually, I was thinking of something much simpler:
```
?foo.bar
```

Where "foo" is a variable, which may be null. I'm not sure why I had a different result last week, but today I have no problems with this expression and null values as "foo". I did stay up late to write the original version of the patch. Maybe I was confused because I was tired.

Looking at the code in ReflectiveAccessorOptimizer, variables can be null and this logic is still compatible with the proposed modification to NullSafe because VariableAccessor is used to retrieve the variable before NullSafe. VariableAccessor passes the variable's value to NullSafe as ctx, and NullSafe is never expected to retrieve variables on its own (NullSafe is "nextNode"):
```
    if (nextNode != null) {
      return nextNode.getValue(vrf.getVariableResolver(property).getValue(), elCtx, vrf);
    }
```

---

By the way, I did a force-push today to fit the "committed by" details. There are no differences in code.
The previous commit was authored by my personal account (SP193) but committed using my work Git account details.

**Comment by tkobayas** [comment]
@sp193 Thank you for the response.

`?foo.bar` is indeed a bit diverged syntax from http://mvel.documentnode.com/#null-safe-bean-navigation .

> Where "foo" is a variable, which may be null. I'm not sure why I had a different result last week
> ...

I tested this:
```
	@Test
	public void testTopLevelNullSafeVariable() {
		String expression = "?myvar.bar";

		Map<String, Object> ctx = new HashMap<>();

		Map<String, Object> vars = new HashMap<>();
		vars.put("myvar", null); // If myvar is added as null, this test passes. If there is no entry (= empty map), it fails.

		Serializable compiledExpr = MVEL.compileExpression(expression);
		Assert.assertNull(MVEL.executeExpression(compiledExpr, ctx, vars));

		Map<String, Object> myvar = new HashMap<>();
		myvar.put("bar", "hello");
		vars.put("myvar", myvar);
		Assert.assertEquals("hello", MVEL.executeExpression(compiledExpr, ctx, vars));
	}
```
If I have the line `vars.put("myvar", null); `, the test passes. If I comment-out the line, the test fails.

The result is the same regardless of your fix for `NullSafe`.

It's not a consistent behavior, but I think it's not supported and it's out of scope of this Issue/PR.

Having that said, I still worry about the `foo.?bar[myvar]` and `foo.?bar.convert(myvar)` use cases. This PR may cause a regression for the use cases (I'm not sure if anyone uses such expressions, though).

As you have suggested:
> If we want it to work with variables, we need to indicate to NullSafe whether the traversal in AST is the at the first node or not. Other modifications (e.g. to allow NullSafe to work with a null context) may be required.

I wrote another PR to make NullSafe work with variables.

https://github.com/mvel/mvel/pull/372

What do you think of the solution?

I will also ask @mariofusco for his thought. (But he is on vacation. Not rushing, Mario)

**Comment by mariofusco** [comment]
Fixed by https://github.com/mvel/mvel/pull/372

**Pull request closed without merging**
