### PR TITLE
Fixed issue #343 - Don't throw an exception when the data doesn't exist !

### PR DESCRIPTION
**Pull request by vampireslove**
Fixed issue #343 - Don't throw an exception when the data doesn't exist
!!

### CODE REVIEW

**Comment by vampireslove** [comment]
Please help me review and merge the code, thank you. 
@mariofusco @MalcolmOdd @tkobayas

**Comment by mariofusco** [comment]
This is a breaking change that will modify the behavior of other software depending on the fact that the exception is thrown when trying to access a missing property. Also **this is not Javascript** where every messed up expression is evaluated at any cost regardless of how wrong it is, always leading to surprising and inconsistent results. If I write an expression trying to use a not existing property I believe that the evaluation of that expression should fail fast and loudly. 

For all these reasons I'm personally against this change, but I'm curious to know what others think about it and open to discuss.

**Comment by MalcolmOdd** [comment]
I do not agree with this change. 

The current behaviour is as intended, this is revealed by the existence of the '?' construct which explicitly  overrides it.

Also the proposed change breaks when executing the expression a second time since the accessor gets optimized (tested with `testOrConditionIfPropertyNotExist()`).

**Comment by vampireslove** [comment]
> This is a breaking change that will modify the behavior of other software depending on the fact that the exception is thrown when trying to access a missing property. Also **this is not Javascript** where every messed up expression is evaluated at any cost regardless of how wrong it is, always leading to surprising and inconsistent results. If I write an expression trying to use a not existing property I believe that the evaluation of that expression should fail fast and loudly.
> 
> For all these reasons I'm personally against this change, but I'm curious to know what others think about it and open to discuss.

The non-existence of data does not mean that an error is reported, it should mean that the rules are met. In actual use, our data comes from various aspects. It is impossible to predict that the data must include the data in the rule expression. However, if an error is reported, the judgment of the data that meets the conditions will be terminated. This is not good. accomplish. for example:  It should have output true, but the result is exception. 
public void testOrConditionIfPropertyNotExist() {
		String expression = "name == 'joy' || age > 10";
		Map<String, Object> paramMap = new HashMap<>();
		paramMap.put("age", 15);
		CompiledExpression compiledExpression = new ExpressionCompiler(expression).compile();
		assertEquals(true, MVEL.executeExpression(compiledExpression, paramMap));
		assertEquals(true, MVEL.eval(expression, paramMap));
	}

**Comment by vampireslove** [comment]
> This is a breaking change that will modify the behavior of other software depending on the fact that the exception is thrown when trying to access a missing property. Also **this is not Javascript** where every messed up expression is evaluated at any cost regardless of how wrong it is, always leading to surprising and inconsistent results. If I write an expression trying to use a not existing property I believe that the evaluation of that expression should fail fast and loudly.
> 
> For all these reasons I'm personally against this change, but I'm curious to know what others think about it and open to discuss.
@mariofusco 
Javascript is support this. 
image

**Comment by vampireslove** [comment]
mvel is an expression judgment rule, not a language, and various situations should be taken into consideration. As far as I know, the following rule engines support the situation we are discussing.
https://github.com/mithunsatheesh/node-rules
https://github.com/aws/event-ruler

Why can others support it, but mvel doesn't? In real environments, the data used for judgment is often unpredictable and unstructured.
@mariofusco @MalcolmOdd

**Comment by adholland** [comment]
Hi @vampireslove @mariofusco,

Just hit this issue on version 2.4.15.Final when an entry in the map does not exist: -
expression - "val='R'; if (additionalValues.setVisible) {val='D'};val");

[Error: could not access: setVisible; in class: java.util.HashMap]
[Near : {... val='R'; if (additionalValues.setVisible) { ....}]

Wondering if these changes are going to make it a new release and if so would it resolve my expression? So with the fix I would expect the if statement to be bypassed.

Thanks for the time, much appreciated.

**Pull request closed without merging**
