### PR TITLE
Disable ASM optimization within OSGi

### PR DESCRIPTION
**Pull request by balazs-zsoldos**
ASM optimizer is really unstable within OSGi. The reasons are the follows:

 - In OSGi, every bundle has a separate ClassLoader
 - The classloader that is used to compile the expressoin, cannot
   always see the classes that are used during runtime
 - For any function call or property access on objects, that are instantiated in other bundles, ASMOptimizer will throw NoClassDefFoundError

This fix:
 - switches off ASMOptimizer if MVEL was loaded as an OSGi bundle
 - does not even initialize DynamicOptimizer class if ASM is not used

As a result of switching off ASMOptimizer, MVEL will be 20% slower (on Java 8, after 15.000 calls (JDK recompiles and enhances classes using reflection after 15.000 calls by default)). That is acceptible.

This fix also fixes another minor issue. I removed ASM and used it as an optional Dependency. However, if DynamicOptimizer is used, during its initialization it calls ASMOptimizer, that needs ASM present. After this fix, ASM could be an optional dependency, and it could be removed from the source of MVEL.

### CODE REVIEW

**Comment by mariofusco** [comment]
Can you please provide a test showing a use case that fails under OSGi?

**Comment by balazs-zsoldos** [comment]
- Bundle A exports and OSGi service with some implementation behind
 - Bundle B uses the OSGi service and drops it as a variable into an MVEL context
 - During the compilation, the classloader of bundle B is used. Classloader of Bundle B sees the interface of the service, but not the implementation.

The use-case above can also be  a problem with standard reflection based behavior:

 - Bundle A exports an OSGi service based on interface
 - Bundle B uses it
 - Bundle A is re-deployed, so the implementation class will be different (even if it has the same name, the type instance is not the same)
 - The MVEL expression will fail next time it is called with the variable that is instantiated with the new implementation class


General solution could also be:

 - Use only those types that are visible for the classLoader that MVEL uses

Example:

 - There is a class MyComparable that implements the Comparable interface
 - The MVEL expression is compiled with the classloader of Bundle B
 - The classLoader sees only Comparable interface but not MyComparable class

In the example above, only the type Comparable should be used for function calls as that can be seen by the passed classloader.

**Comment by lichtin** [comment]
I believe we are experiencing the same issue. Executing expressions very frequently, we suddenly run into 

Caused by: java.lang.NoClassDefFoundError: org/mvel2/compiler/Accessor
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
        at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer$ContextClassLoader.defineClass(ASMAccessorOptimizer.java:2232)
        at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.loadClass(ASMAccessorOptimizer.java:2241)
        at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:737)
        at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeCollection(ASMAccessorOptimizer.java:3010)
        at org.mvel2.optimizers.dynamic.DynamicCollectionAccessor.optimize(DynamicCollectionAccessor.java:90)
        at org.mvel2.optimizers.dynamic.DynamicCollectionAccessor.getValue(DynamicCollectionAccessor.java:67)
        at org.mvel2.ast.InlineCollectionNode.getReducedValueAccelerated(InlineCollectionNode.java:81)
        at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
        at ASMAccessorImpl_18289011541462260645730.getValue(Unknown Source)
        at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:78)
        at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
        at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
        at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:123)
        at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:119)
        at org.mvel2.MVEL.executeExpression(MVEL.java:968)

Is there currently (with 2.2.8.Final) a way to disable ASM optimization?

**Comment by balazs-zsoldos** [comment]
@lichtin You can disable ASM optimization with the _mvel2.disable.jit_ system property.

**Comment by lichtin** [comment]
Thanks. We now work around the issue by providing a suitable TCCL when calling MVEL.executeExpression.
For example:

```
      final ClassLoader tccl = Thread.currentThread().getContextClassLoader();
      try {
        Thread.currentThread().setContextClassLoader(classLoader);
        MVEL.executeExpression(compiledExpression, vars);
      } finally {
        Thread.currentThread().setContextClassLoader(tccl);
      }
```
where "classLoader" is one we know has access to all required classes.

**Comment by lichtin** [comment]
I find the suggested change ("switch off ASMOptimizer if MVEL is loaded as an OSGi bundle") too drastic. It could be sufficient to make disabling ASM optimization more configurable.

**Comment by balazs-zsoldos** [comment]
I ran lots of test before to see the difference between ASM and Reflection optimizer. There was only 20% difference in Java 8 after 15 thousand iterations (the JVM reoptimizes the reflection based calls after that many iterations). I am not sure losing 20% is such a big issue. I also spent days to fix issues for OSGi in the ASM optimizer. I had to give up as the code is very complex and it was not worth to spend more time with it.

**Comment by hoaz** [comment]
We encountered the same issue in our project in OSGI environment. Note that this patch does not fix problem completely. There places in MVEL which call ASM optimizer explicitly, see DynamicCollectionAccessor:

>     _accessor = OptimizerFactory.getAccessorCompiler("ASM").optimizeCollection(pCtx, rootObject, colType,
>         property, start, offset, ctx, elCtx, variableResolverFactory);

As a result we get following exception:

> java.lang.ClassNotFoundException: org.mvel2.compiler.Accessor
>         at java.lang.ClassLoader.findClass(ClassLoader.java:531)[:1.7.0_95]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:425)[:1.7.0_95]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:358)[:1.7.0_95]
>         at java.lang.ClassLoader.defineClass1(Native Method)[:1.7.0_95]
>         at java.lang.ClassLoader.defineClass(ClassLoader.java:800)[:1.7.0_95]
>         at java.lang.ClassLoader.defineClass(ClassLoader.java:643)[:1.7.0_95]
>         at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer$ContextClassLoader.defineClass(ASMAccessorOptimizer.java:2232)
>         at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.loadClass(ASMAccessorOptimizer.java:2241)
>         at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:737)
>         at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeCollection(ASMAccessorOptimizer.java:3010)
>         at org.mvel2.optimizers.dynamic.DynamicCollectionAccessor.optimize(DynamicCollectionAccessor.java:90)
>         at org.mvel2.optimizers.dynamic.DynamicCollectionAccessor.getValue(DynamicCollectionAccessor.java:67)
>         at org.mvel2.ast.InlineCollectionNode.getReducedValueAccelerated(InlineCollectionNode.java:81)
>         at org.mvel2.ast.Contains.getReducedValueAccelerated(Contains.java:37)
>         at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
>         at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:123)
>         at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:119)
>         at org.mvel2.MVEL.executeExpression(MVEL.java:968)
>         ...

**Comment by mariofusco** [comment]
Fixed by https://github.com/mvel/mvel/commit/35595e5b302652a9f5cb6d29420cca0bf6a7ea98

**Comment by rady66** [comment]
In Mvel 2.4.3 on WildFly 16/Open JDK 11, the same issue is observed?:
```
java.lang.ClassNotFoundException: org.mvel2.compiler.Accessor
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:718)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at org.mvel//org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer$ContextClassLoader.defineClass(ASMAccessorOptimizer.java:2245)
	at org.mvel//org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.loadClass(ASMAccessorOptimizer.java:2254)
	at org.mvel//org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:750)
	at org.mvel//org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeSetAccessor(ASMAccessorOptimizer.java:665)
	at org.mvel//org.mvel2.optimizers.dynamic.DynamicSetAccessor.optimize(DynamicSetAccessor.java:83)
	at org.mvel//org.mvel2.optimizers.dynamic.DynamicSetAccessor.setValue(DynamicSetAccessor.java:60)
	at org.mvel//org.mvel2.compiler.CompiledAccExpression.setValue(CompiledAccExpression.java:59)
	at org.mvel//org.mvel2.ast.DeepAssignmentNode.getReducedValueAccelerated(DeepAssignmentNode.java:90)
	at org.mvel//org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
	at org.mvel//org.mvel2.MVEL.executeExpression(MVEL.java:968)
```

**Pull request closed without merging**
