### PR TITLE
Issue113 - mvel throw FastList casting exception under high concurrency

### PR DESCRIPTION
**Pull request by MalcolmOdd**
Issue is caused by a race condition when sometimes the "contains" call is optimized to ASM by ASMAccessorOptimizer.getMethod() before the ArrayList is optimized to FastList. When the ASM-generated class is invoked later, it will fail because the collection is now a FastList and the generated code contains a CHECKCAST for the original class (ArrayList). However, in ASMAccessorOptimizer.getMethod(), the method has been widened to Collection.contains but the CHECKCAST is still created based on the original class. The fix is to create the CHECKCAST based on the method's declaring class.

### CODE REVIEW

**Comment by roidelapluie** [comment]
@mariofusco Can this issue get some attention? We are running into it at high pressure.

**Comment by roidelapluie** [comment]
This is not working:

21:50:46 Tests run: 15, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.037 sec <<< FAILURE! - in org.mvel2.tests.core.ArraysTests
21:50:46 testArrayDefinitionWithCoercion(org.mvel2.tests.core.ArraysTests)  Time elapsed: 0.007 sec  <<< ERROR!
21:50:46 java.lang.ClassCastException: [Ljava.lang.Double; cannot be cast to [D
21:50:46 	at org.mvel2.tests.core.ArraysTests.testArrayDefinitionWithCoercion(ArraysTests.java:55)
21:50:46 
21:50:46 testArrayDefinitionWithCoercion2(org.mvel2.tests.core.ArraysTests)  Time elapsed: 0 sec  <<< ERROR!
21:50:46 java.lang.ClassCastException: [Ljava.lang.Float; cannot be cast to [F
21:50:46 	at org.mvel2.tests.core.ArraysTests.testArrayDefinitionWithCoercion2(ArraysTests.java:61)

**Comment by MalcolmOdd** [comment]
TestArrayDefinitionWithCoercion (as well as a few others) also fails sporadically in the master branch when running all the test at the same time. 
image

**Comment by MalcolmOdd** [comment]
Issue reported by @roidelapluie is a general issue reported as #218 and fixed by #220.
@mariofusco  can this be reviewed and considered for merging? Thx!

**Pull request merged**
